name: Generate Daily Summaries

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 * * * *'  # Run every hour, on the hour (UTC)

jobs:
  generate-summaries:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate summaries for last 7 days
        run: |
          # Calculate dates
          END_DATE=$(date -u +%Y-%m-%d)
          START_DATE=$(date -u -d "7 days ago" +%Y-%m-%d)
          
          # Run the script
          npx ts-node src/generate-daily-summaries.ts "$START_DATE" "$END_DATE" 