name: Bulk Import User Data

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'User ID to import data for'
        required: true
        type: string
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: false
        type: string
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: false
        type: string

jobs:
  dump-import:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      USER_ID: ${{ github.event.inputs.user_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Bulk import user data
        id: import
        run: npm run start:dump

      - name: Generate daily summaries
        if: success() && steps.import.outcome == 'success'
        run: |
          # Use input dates if provided, otherwise use last 30 days
          END_DATE="${{ github.event.inputs.end_date }}"
          START_DATE="${{ github.event.inputs.start_date }}"
          
          if [ -z "$END_DATE" ]; then
            END_DATE=$(date -u +%Y-%m-%d)
          fi
          
          if [ -z "$START_DATE" ]; then
            START_DATE=$(date -u -d "30 days ago" +%Y-%m-%d)
          fi
          
          # Run the script
          npx ts-node src/generate-daily-summaries.ts "$START_DATE" "$END_DATE" 