name: Import Garmin Data

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '15 11 * * *'  # Run every day at 8:15am BRT (11:15 UTC)

jobs:
  import-garmin-data:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Import Garmin data
        id: import
        run: npm start

      - name: Generate daily summaries
        if: success() && steps.import.outcome == 'success'
        run: |
          # Calculate dates for the last day (since this runs multiple times per day)
          END_DATE=$(date -u +%Y-%m-%d)
          START_DATE=$(date -u -d "1 day ago" +%Y-%m-%d)
          
          # Run the script
          npx ts-node src/generate-daily-summaries.ts "$START_DATE" "$END_DATE" 